## This Jupyter notebook contains the instructions for Programming for Data Analysis Assignment 2019

GMIT H.Dip Data Analytics - Academic Year 2019 - 2020

Student: Henk Tjalsma

GMIT email address: G00376321@gmit.ie

## Problem statement

You will find background info, instructions, and research concerning the numpy.random package in Python.

There are four distinct tasks I'm carrying out in this Jupyter notebook:

1. Explain the overall purpose of the package.

2. Explain the use of the “Simple random data” and “Permutations” functions.

3. Explain the use and purpose of at least five “Distributions” functions.

4. Explain the use of seeds in generating pseudorandom numbers.

## Installing Ananconda (which includes NumPy, Jupyter), and Cmder

To answer the four distinct tasks, it was required of me to install some software packages:

* To install NumPy [2] on your local machine, I would advise you to download the anaconda package distribution [8], which installs python [9] and other important python libraries including NumPy, Pandas and Matplotlib (useful for machine learning). 

Anaconda supports Windows, Mac and Linux.

<https://www.anaconda.com/distribution/>

<https://docs.anaconda.com/anaconda/>

Anaconda® is a package manager, an environment manager, a Python/R data science distribution, and a collection of over 1,500+ open source packages. Anaconda is free and easy to install, and it offers free community support.
Anaconda3 includes Python 3.7.


* The Jupyter Notebook [5] is an open-source web application that allows you to create and share documents that contain live code, equations, visualizations and narrative text. Uses include: data cleaning and transformation, numerical simulation, statistical modeling, data visualization, machine learning, and much more.

I'll be using Jupyter Notebook not Jupyter Lab in this assignment (see below the difference between the 2 interfaces):

-> Jupyter Notebook is a web-based interactive computational environment for creating Jupyter notebooks documents. It supports several languages like Python (IPython), Julia, R etc. and is largely used for data analysis, data visualization and further interactive, exploratory computing.

-> JupyterLab is a popular 'new' interface for working with Jupyter Notebooks. It is an interactive development environment for working with notebooks, code and data — and hence extremely extensible.

<https://jupyter.org/install>


* Cmder is a software package which provides a nice command line interface on Windows [10].

<https://cmder.net/>


I use Cmder for changing the working directory on my local machine, i.e. Programming_For_Data_Analysis_Assignment, from there I launch "jupyter notebook" command, and make changes to it.

## Numpy package

First let me explain what Numpy package entails before talking about the random module in the Numpy package, in the next section.

NumPy, an acronym for Numerical Python. NumPy is the fundamental package for scientific computing in Python [11]. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

The central feature of NumPy is the array object class.  Arrays are similar to lists in Python, except that every element  of  an  array  must  be  of  the  same  type,  typically  a  numeric  type  like float or int.  Arrays make operations with large amounts of numeric data very fast and are generally much more efficient than list [14].

At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types, with many operations being performed in compiled code for performance. 

##### There are several important differences between NumPy arrays and the standard Python sequences:

* NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.
* The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory. The exception: one can have arrays of (Python, including NumPy) objects, thereby allowing for arrays of different sized elements.
* NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.
* A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays. In other words, in order to efficiently use much (perhaps even most) of today’s scientific/mathematical Python-based software, just knowing how to use Python’s built-in sequence types is insufficient - one also needs to know how to use NumPy arrays.

In a nutshell, NumPy’s main object is a homogeneous multidimensional array [6]. Unlike python’s array class which only handles one-dimensional array, NumPy’s ndarray class can handle multidimensional array and provides more functionality. 

NumPy’s dimensions are known as axes [18], see below:

![Axes_Displayed](Visual_Description.png)

## 1. Purpose of numpy.random package in Python

The use of randomness is an important part of the configuration and evaluation of machine learning algorithms [19].

An important part of any computer code simulation is the ability to draw random numbers [14]. 

Numpy’s random number routines produce pseudo random numbers using combinations of a BitGenerator to create sequences and a Generator to use those sequences to sample from different statistical distributions [23]:

* BitGenerators: Objects that generate random numbers. These are typically unsigned integer words filled with sequences of either 32 or 64 random bits.
* Generators: Objects that transform sequences of random bits from a BitGenerator into sequences of numbers that follow a specific probability distribution (such as uniform, Normal or Binomial) within a specified interval.

The library contains a few extra probability distributions commonly used in scientific research, as well as a couple of convenience functions for generating arrays of random data. 

##### The module is composed of the following categories:

* Simple random data: rand, randn, randint, and so on
* Permutations: shuffle, permutation
* Distributions: geometric, logistic, normal, and so on

In [1]:
# importing numpy package
import numpy as np

## 2. The use of the “Simple random data” and “Permutations” functions.

##### Simple random data - return a sample (or samples) from the “standard normal” distribution. 

##### Permutations - there are only 2 functions, shuffle, and permutation:

* shuffle(x) - Modify a sequence in-place by shuffling its contents. This function only shuffles the array along the first axis of a multi-dimensional array. The order of sub-arrays is changed but their contents remains the same.

* permutation(x) - Randomly permute a sequence, or return a permuted range. If x is a multi-dimensional array, it is only shuffled along its first index.

## 3. Use and purpose of at least five “Distributions” functions.

https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.poisson.html#numpy.random.poisson

https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.uniform.html#numpy.random.uniform

https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.normal.html#numpy.random.normal

https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.binomial.html#numpy.random.binomial

https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.chisquare.html#numpy.random.chisquare

## 4. Why the use of seeds in generating pseudorandom numbers?

NumPy random seed is simply a function that sets the random seed of the NumPy pseudo-random number generator. It provides an essential input that enables NumPy to generate pseudo-random numbers for random processes.

See below eloborate article:

https://www.sharpsightlabs.com/blog/numpy-random-seed/ [15]

In order to understand “seeding a random number generator” you need to know a little bit about pseudo-random numbers.


#### What is a pseudo-random number?

A pseudo-random number is a number. A number that’s sort-of random. Pseudo-random.
So essentially, a pseudo-random number is a number that’s almost random, but not really random.

A separate article at random.org notes that pseudo-random numbers “appear random, but they are really predetermined”:

https://www.random.org/randomness/

So Pseudo-random numbers are computer generated numbers that appear random, but are actually predetermined.


#### A problem though … computers are deterministic, not random!

There’s a fundamental problem when using computers to simulate or work with random processes. Computers are completely deterministic, not random. Another way of saying this is that if you give a computer a certain input, it will precisely follow instructions to produce an output. 

![Image of Computer](Computer.png)


… And if you later give a computer the same input, it will produce the same output.

If the input is the same, then the output will be the same. THAT’S HOW COMPUTERS WORK.

The behavior of computers is deterministic …

Essentially, the behavior of computers is NOT random.

This introduces a problem: how can you use a non-random machine to produce random numbers?


#### Pseudo-random numbers are generated by algorithms

Computers solve the problem of generating “random” numbers the same way that they solve essentially everything: with an algorithm.

Computer scientists have created a set of algorithms for creating psuedo random numbers, called “pseudo-random number generators.”

These algorithms can be executed on a computer.

As such, they are completely deterministic. However, the numbers that they produce have properties that approximate the properties of random numbers.


#### The pseudo-random numbers appear to be random

That is to say, the numbers generated by pseudo-random number generators appear to be random.

Even though the numbers they are completely determined by the algorithm, when you examine them, there is typically no visisble pattern. See examples 1 and 2 (some pseudo-random numbers with the NumPy randint function).

These numbers are not random, and are in fact completely determined by the algorithm. If you run the same code again, you can see you get the exact same numbers. 


#### Pseudo-random numbers can be re-created exactly

Importantly, because pseudo-random number generators are deterministic, they are also repeatable.

What I mean is that if you run the algorithm with the same input, it will produce the same output.

So you can use pseudo-random number generators to create and then re-create the exact same set of pseudo-random numbers.

See Example 3 and 4, 10 pseudo-random integers between 0 and 7 using numpy.random.randint.

Wehn we generate the pseudo-random integers again second time … notice that we’re using np.random.seed in exactly the same way … it produced the exact same output.

So pseudo random number generators produce numbers that look random, but are 100% determined. 
Determined how though?

Remember what we wrote earlier: computers and algorithms process inputs into outputs. The outputs of computers depend on the inputs. So just like any output produced by 
a computer, pseudo-random numbers are dependent on the input.

THIS is where numpy.random.seed comes in … 

The numpy.random.seed function provides the input (i.e., the seed) to the algorithm that generates pseudo-random numbers in NumPy.


#### The numpy.random.seed provides an input to the pseudo-random number generator

The “random” numbers generated by NumPy are not exactly random. They are pseudo-random … they approximate random numbers, but are 100% determined by the input and the pseudo-random number algorithm.

The np.random.seed function provides an input for the pseudo-random number generator in Python. That’s all the function does!

It allows you to provide a “seed” value to NumPy’s random number generator.

Essentially, if you execute a NumPy function with the same seed, you’ll get the same result.


#### We use numpy.random.seed in conjunction with other numpy functions

Importantly, numpy.random.seed doesn’t exactly work all on its own.

The numpy.random.seed function works in conjunction with other functions from NumPy.

Specifically, numpy.random.seed works with other function from the numpy.random namespace.

So for example, you might use numpy.random.seed along with numpy.random.randint. This will enable you to create random integers with NumPy.

You can also use numpy.random.seed with numpy.random.normal to create normally distributed numbers.

… or you can use it with numpy.random.choice to generate a random sample from an input.

In fact, there are several dozen NumPy random functions that enable you to generate random numbers, random samples, and samples from specific probability distributions.


#### The syntax of NumPy random seed

The syntax of NumPy random seed is extremely simple. There’s essentially only one parameter, and that is the seed value.

![Random_Seed Function](Random_Seed.png)


#### What does np.random.seed(0) do?

We use np.random.seed when we need to generate random numbers or mimic random processes in NumPy.

Computers are generally deterministic, so it’s very difficult to create truly “random” numbers on a computer. Computers get around this by using pseudo-random number generators.

These pseudo-random number generators are algorithms that produce numbers that appear random, but are not really random.

In order to work properly, pseudo-random number generators require a starting input. We call this starting input a “seed.”

The code np.random.seed(0) enables you to provide a seed (i.e., the starting input) for NumPy’s pseudo-random number generator.

NumPy then uses the seed and the pseudo-random number generator in conjunction with other functions from the numpy.random namespace to produce certain types of random outputs.

Ultimately, creating pseudo-random numbers this way leads to repeatable output, which is good for testing and code sharing.

* In the case np.random.seed(0) makes the random numbers predictable [21]. 

Let me show you through some examples, some where random seed is set, others without.

With the seed reset (every time), the same set of numbers will appear every time. 

In [8]:
# First example, created some pseudo-random numbers with the NumPy rand function, provided seed
np.random.seed(0) ; np.random.rand(4)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318])

The numbers in example 1 are not random, and are in fact completely determined by the algorithm. 
If you run the same code again, you’ll get the exact same numbers. 

In [10]:
# Second example, again created some pseudo-random numbers with the rand function, provided seed again
np.random.seed(0) ; np.random.rand(4)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318])

If the random seed is not reset, different numbers appear with every invocation.

In [6]:
# Third example of running the rand function, no seed provided this time
np.random.rand(4)

array([0.56804456, 0.92559664, 0.07103606, 0.0871293 ])

In [9]:
# Fourth example of running the rand function, again no seed provided
np.random.rand(4)

array([0.4236548 , 0.64589411, 0.43758721, 0.891773  ])

So (pseudo-)random numbers work by starting with a number (the seed), multiplying it by a large number, then taking modulo of that product. The resulting number is then used as the seed to generate the next "random" number. When you set the seed (every time), it does the same thing every time, giving you the same numbers.

If you want seemingly random numbers, do not set the seed. If you have code that uses random numbers that you want to debug, however, it can be very helpful to set the seed before each run so that the code does the same thing every time you run it.

To get the most random numbers for each run, call numpy.random.seed(). This will cause numpy to set the seed to a random number obtained from /dev/urandom or its Windows analog or, if neither of those is available, it will use the clock.